[package]
name = "sf-stuff"
version = "0.1.0"
edition = "2021"

[dependencies]
sf-api = { git = "https://github.com/the-marenga/sf-api.git", version = "0.2.0" }
tokio = { version = "1.38", features = ["full"] }
